name: Build TWRP for Galaxy A13

on:
  push:
    branches:
      - main  # أو أي فرع آخر ترغب في استخدامه
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # تحديث إلى الإصدار 4

      - name: Set up JDK
        uses: actions/setup-java@v4  # تحديث إلى الإصدار 4
        with:
          java-version: '11'  # تأكد من استخدام الإصدار المناسب
          distribution: 'adopt'  # أو 'temurin' أو 'zulu' حسب التوزيعة التي تفضلها

      - name: Install required packages
        run: |
          sudo apt-get update
          sudo apt-get install -y git wget curl unzip bison g++-multilib gcc-multilib \
          libncurses5-dev lib32z1 lib32stdc++6 python3 python3-pip

      - name: Download and set up Android SDK
        run: |
          mkdir -p $HOME/Android/Sdk/cmdline-tools
          cd $HOME/Android/Sdk/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-6609375_latest.zip
          unzip commandlinetools-linux-6609375_latest.zip
          rm commandlinetools-linux-6609375_latest.zip
          # Move the extracted folder to 'latest' if it exists
          if [ -d "cmdline-tools" ]; then
              mv cmdline-tools latest
          elif [ -d "tools" ]; then
              mv tools latest  # Some versions may extract to 'tools' instead of 'cmdline-tools'
          else
              echo "cmdline-tools or tools directory not found!"
              exit 1
          fi
          yes | $HOME/Android/Sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/Android/Sdk --licenses
          $HOME/Android/Sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/Android/Sdk "platform-tools" "platforms;android-30" "build-tools;30.0.3"

      - name: Set up environment
        run: |
          echo "export ANDROID_HOME=$HOME/Android/Sdk" >> $GITHUB_ENV
          echo "export PATH=$ANDROID_HOME/platform-tools:$ANDROID_HOME/cmdline-tools/latest/bin:$PATH" >> $GITHUB_ENV

      - name: Build TWRP
        run: |
          cd https://github.com/k7886686/twrp_samsung_a13ve  # تأكد من الانتقال إلى مجلد المشروع الصحيح
          . build/envsetup.sh  # تأكد من أن هذا هو المسار الصحيح
          lunch twrp_a13ve-eng  # تأكد من أن هذا هو اسم الجهاز الصحيح
          make -j$(nproc)

      - name: Upload TWRP image
        uses: actions/upload-artifact@v4  # تحديث إلى الإصدار 4
        with:
          name: twrp-image
          path: out/target/product/a13ve/recovery.img  # تأكد من أن هذا هو المسار الصحيح
